version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: db-postgres
    environment:
      POSTGRES_DB: bankrestservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
